# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: gen
generate:
  std-http-server: true
  models: true
output: api/gen/api.gen.go
# ...
